#!/bin/bash
#PBS -N protein_clm_training          
#PBS -q A100
#PBS -l select=1:ncpus=32 
#PBS -l walltime=24:00:00    
#PBS -o outputs/clm_output.txt
#PBS -e outputs/clm_error.txt

# Load necessary modules
module use /app/utils/modules && module load anaconda3-2022
source activate MyPytorch2.0

JOB_HOME_DIR="$HOME/src/python/"

cd $JOB_HOME_DIR

# Run your Python program
accelerate launch training/run_clm.py --run_name SmolLM2-1.7B-Instruct-CPPT \
    --base_model_path /ddn/data/fcit/jghazialharbi/models/base/SmolLM2-1.7B-Instruct \
    --lora_model_path /ddn/data/fcit/jghazialharbi/models/adapter/SmolLM2-1.7B-Instruct \
    --dataset_path /ddn/data/fcit/jghazialharbi/data/uniref50 \
    --output_dir /ddn/data/fcit/jghazialharbi/experim/SmolLM2-1.7B \
    --text_column sequence \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --num_train_epochs 1 \
    --lr 0.0003

conda deactivate
module purge
